name: Setup Credentials

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to set up'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - production

permissions:
  contents: write
  pull-requests: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create appsettings.Development.json
        if: github.event.inputs.environment == 'development'
        run: |
          echo '${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}' > temp_credentials.json
          echo '{
            "Logging": {
              "LogLevel": {
                "Default": "Information",
                "Microsoft.AspNetCore": "Warning"
              }
            },
            "ConnectionStrings": {
              "DefaultConnection": "Server=localhost;Database=ReceiptProject;User=root;Password=540770;Port=3306;"
            },
            "GoogleCloudCredentials": '"$(cat temp_credentials.json)"'
          }' > appsettings.Development.json
          rm temp_credentials.json

      - name: Create Pull Request
        if: github.event.inputs.environment == 'development'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update credentials for development"
          title: "Update development credentials"
          body: "This PR updates the development credentials from GitHub Secrets"
          branch: update-credentials
          base: main
          delete-branch: true
